apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: test
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  rbd:
    monitors:
      - 10.122.1.108:6789
    pool: mysqlpool
    image: cloudzone
    user: admin
    secretRef:
      name: ceph-secret
    fsType: ext4
    readOnly: false
  persistentVolumeReclaimPolicy: Recycle